# Generated by Django 6.1 on 2026-08-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0002_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='example_code',
            field=models.TextField(blank=True),
        ),
    ]
