# Generated by Django 6.1 on 2026-08-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python', '0003_topics_example_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
